import localFont from "next/font/local";
import "./globals.css";   

 
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <>
  <meta charSet="utf-8" /> 
 
  {/* Free Cookie Consent Notice Banner by ComplyDog at https://complydog.com/free-cookie-consent-banner */}
  <title>
    hadizproductions
  </title>
  <meta
    name="description"
    content="hadizproductions is a real estate agency based in Tbilisi Georgia"
  />
  <meta
    name="keywords"
    content="Prestwich Estate Agents,Lettings Agents,Property For Sale,Property For Rent,Property,Houses,Homes"
  />
  <meta name="author" content="www.acquaintcrm.co.uk" />
  <meta name="robots" content="index,follow,noodp,noydir" />
  <meta name="websiteversion" content="2.2" />
 
  <link
    href="https://fonts.googleapis.com/css?family=Roboto+Slab|Open+Sans|Marck+Script"
    rel="stylesheet"
    type="text/css"
  />
  
  <link rel="icon" type="image/png" href="https://ucarecdn.com/2fae4aff-4e02-4ef4-a21d-f5109e0a7a25/logo.jpg" />
  <link rel="shortcut icon" type="x-icon" href="https://ucarecdn.com/2fae4aff-4e02-4ef4-a21d-f5109e0a7a25/logo.jpg" />
   
  <link
    rel="alternate"
    type="application/rss+xml"
    title="hadizproductions & Company"
    href="images/AUBR/rss.xml"
  />
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="hadizproductions" />
  <meta
    name="twitter:description"
    content="hadizproductions are one of north Manchester's leading estate agents covering Prestwich, Salford & Whitefield"
  />
  <meta
    name="twitter:image"
    content="https://www.hadizproductions/images/AUBR/logo.png"
  />
  <meta property="og:title" content="Estate Agents In Prestwich, Manchester" />
  <meta
    property="og:description"
    content="hadizproductions are one of north Manchester's leading estate agents covering Prestwich, Salford & Whitefield"
  />
  <meta property="og:type" content="website" />
  <meta
    property="og:image"
    content="https://www.hadizproductions/images/AUBR/logo.png"
  />
  {/* Google Analytics */}
  {/* End Google Analytics */}
  {/* Mobile Meta Tag */}
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  {/* IE6-8 support of HTML5 elements */}
  {/*[if lt IE 9]>
	   
	<![endif]*/}
  {/* Bootstrap CSS */}
  <link href="css/bootstrap.min.css" rel="stylesheet" />
  {/* Extra CSS - moved from stylesheet.css by GJ */}
  <link href="css/font-awesome.min.css" rel="stylesheet" />
  <link href="css/cozy-real-estate-font.css" rel="stylesheet" />
  <link href="css/owl.transitions.css" rel="stylesheet" />
  {/* Revolution Slider CSS settings */}
  <link
    rel="stylesheet"
    type="text/css"
    href="rs-plugin/css/settings.css"
    media="screen"
  />
  {/* Modernizr */}
  {/* Head place holder */}
  {/* WebScriptHeader place holder */}
  <link
    href="https://webutils.acquaintcrm.co.uk/css/sweetalert2.css"
    rel="stylesheet"
  />
  {/* Site Specific Styles */}
  <link
    rel="stylesheet"
    type="text/css"
    href="images/AUBR/stylesheet.css@cacheversion=2.css"
  />
  <link rel="stylesheet" type="text/css" href="css/system.css" />
  <link
    rel="stylesheet"
    type="text/css"
    href="images/AUBR/stylesheet2.css@cacheversion=2.css"
  />
  <link
    rel="stylesheet"
    type="text/css"
    href="images/AUBR/MaintenanceRequest.css"
  />
         <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
</>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
